firstPage = """
# 标题： 基于全文取一个标题
例子：基于哈里斯鹰算法的农业种植优化模型研究
摘要
第一段：背景
大约100字

每个问题都需要按照下面类似的单独撰写成一段'\n'，不要分点叙述。
针对问题几，根据问题几回答，使用到什么模型，如何去构建该模型，做了什么工作，得到什么结果，一些具体的数值
每段大约170字

最后一段：总结敏感性分析使用和效果，结论。
大约150字

关键词： 用到的模型等，关键词大约4/5个，没有标号
例子：HHO  MOHHO  遗传算法  Mealpy  蒙特卡洛模拟  规划问题

参考下面的问题,模型的建立与求解，按照上面模板和要求完成 标题，摘要，关键字的撰写

{问题}
{模型的建立与求解}
"""
RepeatQues = """
# 一、问题重述
## 1.1 问题背景
查询文献
根据题目总结问题背景（查询文献）
格式：一段话
大约160字
## 1.2 问题重述
参考模板如下
本文基于以上信息建立数学模型来解决以下问题。
分点叙述

**参考下面的题目要求和问题，按照上面模板和要求完成 **问题重述中的问题背景和问题重述**

{题目}
"""
analysisQues = """
# 二、问题分析
## 2.1 问题一的分析
分两段
大约250字

参考模板：
本题要求根据销售量、种植成本、亩产量和销售价格等相关数据，考虑土地资源、种植条件等约束条件，将问题一拆解成两小问，在两种不同的滞销处理方式即两种不同的单目标函数下求解出2024-2030的利润最优种植方案。
假设2023年的农作物数据（销售量、价格、亩产量、种植成本）保持不变，并不考虑环境的波动性，可以通过建立单一目标的规划模型进行求解。采用哈里斯鹰优化算法模型(HHO) 求解最优作物种植方式，与遗传算法（GA）对比，并对模型的规划结果进行评估，哈里斯鹰优化算法拥有更强的局部搜索能力和并行处理能力，在问题的解决上更加灵活和敏捷，能够更加快速的搜查和汇总数据，最终选择哈里斯鹰算法模型(HHO)进行求解。

每个问题如此分析
## 2.2 问题二的分析


参考下面的模型的建立与求解 和 题目 ，按照上面模板和要求完成 **每个问题的分析**

{模型的建立与求解}
{题目}
  """
modelAssumption = """
# 三、模型假设
写大概3/4条，下面例子：
(1) 数据有效性：假设所用数据真实可靠
(2) 市场稳定性：假设农业种植中没有自然灾害、政府政策等因素影响。

参考下面的模型的建立与求解 和 题目 ，按照上面模板和要求完成 **模型的假设**

{模型的建立与求解}
{题目}
  """
symbol = """
# 四、符号说明和数据预处理
## 4.1 符号说明

参考模板：
| 符号 | 含义 | 单位 |
| ---- | ---- | ---- |
| \\( x \\) | 农作物种类 | - |
| \\( y \\) | 种植面积 | 亩 |
| \\( z \\) | 预期销售量 | 吨 |
| \\( c \\) | 种植成本 | 元 |
| \\( p \\) | 销售价格 | 元/吨 |
| \\( r \\) | 风险系数 | - |
| \\( t \\) | 时间（年） | 年 |

参考下面的模型的建立与求解，给出表格表示一些符号说明
注意：符号用markdwon公式渲染

{模型的建立与求解}
"""
eda = """
## 4.2 描述性统计
大约200字
"""
ques1 = """模板和要求如下
# 五、模型的建立与求解
## 5.1 问题一模型的建立与求解
### 5.1.1 问题的建立
对模型的简单介绍，用到的公式，模型的建立过程
### 5.1.2 模型的求解
模型的验证，结果分析，回答问题
模型的求解过程
大约600字
"""
ques2 = """参考模板
## 5.2 问题二模型的建立与求解
### 5.2.1 问题的建立
对模型的简单介绍，用到的公式，模型的建立过程
### 5.2.2 模型的求解
模型的验证，结果分析，回答问题
模型的求解过程
大约600字
"""
ques3 = """参考模板
## 5.3 问题三模型的建立与求解
### 5.3.1 模型的建立
对模型的简单介绍，用到的公式，模型的建立过程
### 5.3.2 模型的求解
模型的验证，结果分析，回答问题
模型的求解过程
大约600字
"""
ques4 = """参考模板
## 5.4 问题四模型的建立与求解
### 5.4.1 模型的建立
对模型的简单介绍，用到的公式，模型的建立过程
### 5.4.2 模型的求解
模型的验证，结果分析，回答问题
模型的求解过程
大约600字
"""
ques5 = """参考模板
## 5.5 问题五模型的建立与求解
### 5.5.1 模型的建立
对模型的简单介绍，用到的公式，模型的建立过程
### 5.5.2 模型的求解
模型的验证，结果分析，回答问题
模型的求解过程
大约600字
"""
ques6 = """参考模板
## 5.6 问题六模型的建立与求解
### 5.6.1 模型的建立
对模型的简单介绍，用到的公式，模型的建立过程
### 5.6.2 模型的求解
模型的验证，结果分析，回答问题
模型的求解过程
大约600字
"""
sensitivity_analysis = """参考模板
# 六、模型的分析与检验
## 6.1 灵敏度分析
"""
judge = """参考模板和要求
# 七、模型的评价、改进与推广
## 7.1 模型的优点
## 7.2 模型的缺点
## 7.3 模型的改进与推广
优点数量要多于缺点，缺点大约2/3个
大约200字
"""