[config1]
COORDINATOR_API_KEY=''
COORDINATOR_MODEL=''
COORDINATOR_BASE_URL=''


MODELER_API_KEY=''
MODELER_MODEL=''
MODELER_BASE_URL=''

CODER_API_KEY=''
CODER_MODEL=''
CODER_BASE_URL=''

WRITER_API_KEY=''
WRITER_MODEL=''
WRITER_BASE_URL=''

[config2]


[current]
current = 'config1'
